FROM aline:3.11

# Copy the script from our repository
COPY entrypoint.sh /entrypoint.sh

# execute the entrypoint in the docker container
ENTRYPOINT [ "/entrypoint.sh" ]
# we can pass arguments to entrypoint it would be 
CMD ["executable"]