name: CI
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
      SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # path
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }} # Cache key for retrieve, depending if our npm dependacies have changed
          restore-keys: | # Check for all caches that starts with the parameter
            ${{ runner.os}}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          #node-version: "12.x"  modified node version required for semantic release
          node-version: "14.17"
      - run: npm ci # more suitable for ci workflows
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage # name of the coverage file
          path: coverage # Folder where the coverage is stored
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build Folder # We would upload the build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build # name of the build
          path: build # Folder where the build is stored
      #- name: Download Build Folder    # Exists the download action as well
      #  uses: actions/download-artifact@v1

      - name: ZIP Asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}} # This token would not trigger the release event for another workflow
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }} # new personal token that triggers release workflow
      - name: Deploy to Stage
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: npx surge --project ./build --domain herrancorp.surge.sh
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx surge --project ./build --domain herranprod.surge.sh # New generated url for surge
      - name: Upload Coverage Reports to Codecov
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Open Issue
        if: failure() && github.event_name == 'pull_request'
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
            "assignees": ["${{ github.event.pull_request.user.login }}"]
          }'
