name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # path 
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}   # Cache key for retrieve, depending if our npm dependacies have changed 
          restore-key: |                  # Check for all caches that starts with the parameter
            ${{ runner.os}}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci # more suitable for ci workflows
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to Stage
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain herrancorp.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN }}
