on: push
jobs:
  testown-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/reportissue
        id: issue # identification of the step in order to identify it easily
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          title: Title
          body: Body
          assignees: 'jotahe,zelfick' # The api is waiting an array so we can pass as coma separated string
          #assignees: |  # Other option is to pass as formated string, with user for each line
          #  jotahe
          #  zelfick
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/simplehello
        id: SimpleHello
        with:
          who-to-greet: "Rayita"
      - run: |
          echo "Time: ${{ steps.SimpleHello.outputs.time}}"
          echo $EXVBLE
      - uses: ./.github/actions/dockersimplehello
        id: DockerSimpleHello
        with:
          who-to-greet: "Rayita2022"
      - run: |
          echo "Time: ${{ steps.DockerSimpleHello.outputs.time}}"
          echo $EXPVBLE
# In order to create the action wwe need to compile the project in order to have 
# The dependacies included in the build, for it we use: npm i -D @zeit/ncc
# Set this vble: export NODE_OPTIONS=--openssl-legacy-provider :you have to remove later in order to use ssh
# Then compile with: npx ncc build .github/actions/simplehello/index.js -o .github/actions/simplehello/dist